package dao.shop;
// Generated 06.12.2015 13:19:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Shop generated by hbm2java
 */
@Entity
@Table(name="shop"
    ,catalog="dbshop"
)
public class Shop  implements java.io.Serializable {


     private int shopId;
     private String name;
     private float x;
     private float y;

    public Shop() {
    }

    public Shop(int shopId, String name, float x, float y) {
       this.shopId = shopId;
       this.name = name;
       this.x = x;
       this.y = y;
    }
   
     @Id 

    
    @Column(name="shopId", nullable=false)
    public int getShopId() {
        return this.shopId;
    }
    
    public void setShopId(int shopId) {
        this.shopId = shopId;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="x", nullable=false, precision=12, scale=0)
    public float getX() {
        return this.x;
    }
    
    public void setX(float x) {
        this.x = x;
    }

    
    @Column(name="y", nullable=false, precision=12, scale=0)
    public float getY() {
        return this.y;
    }
    
    public void setY(float y) {
        this.y = y;
    }




}


