package dao.shop;
// Generated 22.11.2015 13:40:00 by Hibernate Tools 4.3.1


import dao.history.History;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shop generated by hbm2java
 */
@Entity
@Table(name="shop"
    ,catalog="dbshop"
)
public class Shop  implements java.io.Serializable {


     private int shopId;
     private String name;
     private String country;
     private String town;
     private String address;
     private Set<History> histories = new HashSet<History>(0);

    public Shop() {
    }

	
    public Shop(int shopId, String name, String country, String town, String address) {
        this.shopId = shopId;
        this.name = name;
        this.country = country;
        this.town = town;
        this.address = address;
    }
    public Shop(int shopId, String name, String country, String town, String address, Set<History> histories) {
       this.shopId = shopId;
       this.name = name;
       this.country = country;
       this.town = town;
       this.address = address;
       this.histories = histories;
    }
   
     @Id 

    
    @Column(name="shopId", unique=true, nullable=false)
    public int getShopId() {
        return this.shopId;
    }
    
    public void setShopId(int shopId) {
        this.shopId = shopId;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="country", nullable=false, length=100)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="town", nullable=false, length=100)
    public String getTown() {
        return this.town;
    }
    
    public void setTown(String town) {
        this.town = town;
    }

    
    @Column(name="address", nullable=false, length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shop")
    public Set<History> getHistories() {
        return this.histories;
    }
    
    public void setHistories(Set<History> histories) {
        this.histories = histories;
    }




}


