package dao.comment;
// Generated 06.12.2015 13:19:59 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name="comment"
    ,catalog="dbshop"
)
public class Comment  implements java.io.Serializable {


     private Integer idcomment;
     private Integer iduser;
     private Date datacom;
     private String content;

    public Comment() {
    }

	
    public Comment(Date datacom, String content) {
        this.datacom = datacom;
        this.content = content;
    }
    public Comment(Integer iduser, Date datacom, String content) {
       this.iduser = iduser;
       this.datacom = datacom;
       this.content = content;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcomment", unique=true, nullable=false)
    public Integer getIdcomment() {
        return this.idcomment;
    }
    
    public void setIdcomment(Integer idcomment) {
        this.idcomment = idcomment;
    }

    
    @Column(name="iduser")
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datacom", nullable=false, length=10)
    public Date getDatacom() {
        return this.datacom;
    }
    
    public void setDatacom(Date datacom) {
        this.datacom = datacom;
    }

    
    @Column(name="content", nullable=false, length=65535)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


