package dao.products;
// Generated 06.12.2015 13:19:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="dbshop"
)
public class Products  implements java.io.Serializable {


     private int id;
     private String name;
     private String author;
     private String country;
     private String direction;
     private String genre;
     private String pathartwork;
     private String price;
     private String size;
     private String technique;

    public Products() {
    }

	
    public Products(int id, String price) {
        this.id = id;
        this.price = price;
    }
    public Products(int id, String name, String author, String country, String direction, String genre, String pathartwork, String price, String size, String technique) {
       this.id = id;
       this.name = name;
       this.author = author;
       this.country = country;
       this.direction = direction;
       this.genre = genre;
       this.pathartwork = pathartwork;
       this.price = price;
       this.size = size;
       this.technique = technique;
    }
   
     @Id 

    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="author", length=100)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    
    @Column(name="country", length=50)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="direction", length=45)
    public String getDirection() {
        return this.direction;
    }
    
    public void setDirection(String direction) {
        this.direction = direction;
    }

    
    @Column(name="genre", length=45)
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }

    
    @Column(name="pathartwork")
    public String getPathartwork() {
        return this.pathartwork;
    }
    
    public void setPathartwork(String pathartwork) {
        this.pathartwork = pathartwork;
    }

    
    @Column(name="price", nullable=false, length=16777215)
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }

    
    @Column(name="size", length=45)
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }

    
    @Column(name="technique", length=100)
    public String getTechnique() {
        return this.technique;
    }
    
    public void setTechnique(String technique) {
        this.technique = technique;
    }




}


