package dao.history;
// Generated 06.12.2015 13:19:59 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * History generated by hbm2java
 */
@Entity
@Table(name="history"
    ,catalog="dbshop"
)
public class History  implements java.io.Serializable {


     private int id;
     private int shopId;
     private int productId;
     private int userId;
     private Date databuy;

    public History() {
    }

    public History(int id, int shopId, int productId, int userId, Date databuy) {
       this.id = id;
       this.shopId = shopId;
       this.productId = productId;
       this.userId = userId;
       this.databuy = databuy;
    }
   
     @Id 

    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="shopID", nullable=false)
    public int getShopId() {
        return this.shopId;
    }
    
    public void setShopId(int shopId) {
        this.shopId = shopId;
    }

    
    @Column(name="productID", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }

    
    @Column(name="userID", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="databuy", nullable=false, length=10)
    public Date getDatabuy() {
        return this.databuy;
    }
    
    public void setDatabuy(Date databuy) {
        this.databuy = databuy;
    }




}


